# -*- mode: shell-script-*-
#
# This file is loaded by login shells.
# On my machines the terminal emulators run login shells by default.
# However, subshells for instance are not login shells.
# Here I mostly define environment variables, which in any case are passed on to subshells.

[ ${TERM} == "dumb" ] && return

##
#  First load the generic profile
##

if [ -f "$HOME/.profile" ]; then
    source "$HOME/.profile"
fi

##
#  Environment variables
##

# Language
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Terminal and colors
export TERM=xterm-256color
export CLICOLOR=1

# Bash settings: history, globs
export HISTCONTROL=ignorespace:erasedups
export HISTIGNORE="ls:[bf]g:cd:exit:pwd"
export GLOBIGNORE=.:..

# Building the path
if [ "$(uname -s)" == "Darwin" ]; then
    [ -d "/usr/local/sbin" ] && PATH="/usr/local/sbin:$PATH"
    # Macports path for OS X
    macportsprefix="/opt/local"
    macportspath=( "sbin" "bin" "libexec/gnubin" )
    for dir in "${macportspath[@]}"; do dir="${macportsprefix}/$dir"; [ -d "$dir" ] && PATH="$dir:$PATH"; done
    PATH="${HOME}/Library/Python/3.10/bin:$PATH"
    [ -d "${macportsprefix}/share/man" ] && export MANPATH="${macportsprefix}/share/man:$MANPATH"
    export HOMEBREW_PREFIX="/opt/homebrew";
    export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
    export HOMEBREW_REPOSITORY="/opt/homebrew";
    PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
    export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
    export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
fi
[ -d "${HOME}/bin" ] && PATH="$HOME/bin:${PATH}"
[ -d "${HOME}/scripts" ] && PATH="${HOME}/scripts:${PATH}" # Custom scripts
[ -d "${HOME}/scripts/crypto" ] && PATH="${HOME}/scripts/crypto:${PATH}" # Custom scripts
[ -d "${HOME}/scripts/fms-scripts" ] && PATH="${HOME}/scripts/fms-scripts:${PATH}" # Custom scripts
[ -d "${HOME}/scripts/ghost-scripts" ] && PATH="${HOME}/scripts/ghost-scripts:${PATH}" # Custom scripts
export PATH

# Library path
if [ "$(uname -s)" == "Darwin" ]; then
    LIB_PATH="DYLD_LIBRARY_PATH"
else
    LIB_PATH="LD_LIBRARY_PATH"
fi

# Default programs
export EDITOR="emacs -nw"
if command -v most > /dev/null 2>&1; then export PAGER="most"; else export PAGER="less"; fi
export MANPAGER="$PAGER"
export BAT_PAGER="less"
export BAT_THEME="Solarized (dark)"

##
#  Greetings
##
Cyan='\x1B[0;36m'         # Cyan
NC="\x1B[m"               # Color Reset
echo -e "${Cyan}BASH ${BASH_VERSION%.*} - $(date)${NC}"


##
#  Sourcing bashrc if the shell is interactive
##

if [[ $- == *i* ]] && [ -f "$HOME/.bashrc" ]; then
    source "$HOME/.bashrc"
fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
CONDA="$HOME/miniconda3/bin/conda"
__conda_setup="$($CONDA 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup CONDA
# <<< conda initialize <<<

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
